import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

export type Language = "zh" | "en";

export interface Translations {
    [key: string]: string;
}

export const translations: Record<Language, Translations> = {
    zh: {
        title: "Sui 商品追溯平台",
        connectWallet: "连接钱包",
        pleaseConnectWallet: "请连接您的钱包",
        loading: "加载中...",
        productManagement: "📦 商品管理",
        scanner: "🔍 扫码验证",
        productTraceabilityManagement: "商品追溯管理",
        traceFlow: "发布商品 → 上链 → 生成追溯码 → 消费者扫码验证",
        totalProducts: "📦 商品总数",
        pendingChain: "🟡 待上链",
        onChain: "🟢 已上链",
        processing: "🔄 上链中",
        publishProduct: "+ 发布商品",
        searchPlaceholder: "搜索商品名称或描述...",
        all: "全部",
        batchUpload: "批量上链",
        allProducts: "全部商品",
        category: "分类",
        extendedFields: "扩展字段",
        status: "状态",
        qrcodeCount: "追溯码数量",
        createTime: "创建时间",
        actions: "操作",
        noProducts: "暂无商品",
        noProductsTip: "还没有发布任何商品，点击上方按钮发布第一个商品",
        noPendingTip: "没有待上链的商品",
        noOnChainTip: "还没有已上链的商品",
        tip: "💡 提示：发布商品后上链，才能生成追溯码供消费者扫码验证",
        detail: "详情",
        upload: "上链",
        delete: "删除",
        generateQRCode: "生成追溯码",
        newProduct: "新增商品",
        basicInfo: "基础信息（必填）",
        productName: "商品名称",
        productDescription: "商品描述",
        selectCategory: "请选择商品分类",
        extendedFieldsOptional: "扩展字段（可选）",
        addField: "+ 添加字段",
        fieldName: "字段名称",
        fieldValue: "字段值",
        text: "文本",
        date: "日期",
        number: "数字",
        saveDraft: "保存草稿",
        saveAndUpload: "保存并上链",
        cancel: "取消",
        close: "关闭",
        saveChanges: "保存修改",
        saved: "保存中...",
        uploading: "上链中...",
        productDetail: "商品详情",
        edit: "编辑",
        chainInfo: "链上信息",
        chainId: "链上ID",
        blockHeight: "区块高度",
        uploadTime: "上链时间",
        statistics: "统计信息",
        scanCount: "扫码次数",
        nftClaim: "NFT领取",
        claimNFT: "领取NFT",
        claiming: "领取中...",
        productVerification: "🔍 商品追溯验证",
        verificationDesc: "输入追溯码ID，验证商品真伪，首次扫码可领取NFT",
        enterQRCode: "请输入追溯码ID...",
        scanVerify: "扫码验证",
        processingText: "处理中...",
        verificationResult: "验证结果",
        productAuthentic: "✅ 商品真实",
        productInfo: "🏷️ 商品信息",
        scanHistory: "📊 扫码记录",
        scannedTimes: "已被扫描",
        times: "次",
        alreadyClaimed: "已领取",
        canClaim: "可领取",
        firstScanTime: "首次扫码时间",
        firstScanner: "首次扫码者",
        congratsFirstScan: "🎉 恭喜！您是首次扫码者，可以领取NFT",
        notFirstScan: "⚠️ 您不是首次扫码者，无法领取NFT",
        nftAlreadyClaimed: "💡 NFT已被领取，您可以继续扫码验证商品真伪",
        violetTheme: "🟣 紫罗兰",
        blueTheme: "🔵 深海蓝",
        chinese: "简体中文",
        english: "English",
        food: "食品",
        clothing: "服装",
        electronics: "电子产品",
        cosmetics: "化妆品",
        agricultural: "农产品",
        medicine: "医药",
        other: "其他",
        pleaseFillBasic: "请填写完整的基础信息",
        pleaseEnterFieldName: "请输入字段名称",
        productCreated: "商品已创建并上链！",
        productSaved: "商品已保存为草稿！",
        fieldAdded: "字段添加成功",
        confirmDeleteField: "确定要删除此字段吗？",
        confirmDeleteProduct: "确定要删除此商品吗？",
        deleted: "商品已删除",
        cannotDeleteOnChain: "已上链的商品无法删除",
        uploadConfirm: "确定要将选中的",
        itemsToChain: "件商品上链吗？",
        uploadingBatch: "正在批量上链中，请稍后刷新查看状态",
        pleaseSelectProducts: "请先选择要上链的商品",
        qrcodeGenerated: "✅ 追溯码生成成功！",
        qrcodeId: "📋 追溯码ID",
        qrcodeTip: "💡 请复制此ID用于扫码验证",
        scanning: "正在上链中，请稍后刷新查看状态",
        nftClaimed: "✅ NFT领取成功！",
        nftId: "📋 NFT ID",
        nftProductId: "🏷️ 商品ID",
        nftClaimTime: "⏰ 领取时间",
        claimFailed: "❌ 领取失败！您不是首次扫码者或NFT已被领取",
        qrcodeNotFound: "❌ 未找到该追溯码，请检查ID是否正确",
        pleaseEnterQrcode: "请输入追溯码ID",
        scanFailed: "❌ 扫码验证失败，请稍后重试",
        productQuantity: "📦 商品数量",
        quantityTip: "（最大10000）",
        qrcodeProgress: "📊 追溯码进度",
        batchGenerateQRCode: "批量生成追溯码",
        enterQrcodeCount: "请输入生成数量",
        remaining: "剩余",
        allQrcodesGenerated: "⚠️ 所有追溯码已生成完毕",
        invalidCount: "❌ 无效的数量",
        batchQrcodeGenerated: "✅ 批量追溯码生成成功！",
        generatedCount: "生成数量",
        qrcodeUrls: "追溯码验证链接",
        purple: "紫色",
        blue: "蓝色",
        enterpriseInfo: "企业信息",
        productCount: "商品数量",
        createdAt: "创建时间",
        disconnect: "断开连接",
        back: "返回",
        editEnterpriseProfile: "编辑企业信息",
        savedSuccessfully: "保存成功！",
        enterpriseName: "企业名称",
        enterEnterpriseName: "请输入企业名称",
        enterDescription: "请输入企业描述",
        walletAddress: "钱包地址",
        enterpriseNotFound: "未找到企业信息",
        save: "保存",
        generatedQrcodes: "已生成追溯码",
        showQrcodes: "显示二维码",
        hideQrcodes: "隐藏二维码",
        generating: "生成中",
        copyLink: "复制链接",
        claimed: "已领取",
        unclaimed: "未领取",
        copied: "已复制！",
        home: "首页",
        dashboard: "控制台",
        globalPlatform: "全球平台",
        heroTitle: "全球商品追溯码平台",
        heroSubtitle: "基于 Sui 区块链技术，为全球企业提供公开、透明、永久保存的商品追溯解决方案",
        getStarted: "开始使用",
        scanNow: "立即扫码",
        globalCoverage: "全球覆盖",
        globalCoverageDesc: "支持全球范围的商品追溯，无论您的商品销往何处，都能实现全程追踪",
        openTransparent: "公开透明",
        openTransparentDesc: "所有追溯数据上链存储，任何人都可以验证商品信息的真实性",
        freeToUse: "免费使用",
        freeToUseDesc: "企业可以免费创建商品、生成追溯码、上链存储，零成本启动",
        chainPermanent: "链上永久保存",
        chainPermanentDesc: "数据存储在区块链上，不可篡改、永久保存，确保商品信息的长期有效性",
        nftVerification: "NFT验证",
        nftVerificationDesc: "消费者扫码验证商品真伪，首次验证可领取NFT奖励",
        fastEfficient: "高效快速",
        fastEfficientDesc: "基于 Sui 区块链的高性能特性，交易确认快，体验流畅",
        qrcodesGenerated: "追溯码生成",
        enterprises: "企业用户",
        uptime: "系统可用性",
        cost: "使用成本",
        howItWorks: "如何运作",
        howItWorksDesc: "简单四步，完成商品追溯全流程",
        createProduct: "创建商品",
        createProductDesc: "在控制台创建商品信息，设置商品数量和扩展字段",
        uploadChain: "上链存储",
        uploadChainDesc: "将商品信息上传至 Sui 区块链，获得链上ID",
        generateQrcode: "生成追溯码",
        generateQrcodeDesc: "批量生成加密追溯码，每个追溯码对应唯一的验证链接",
        scanVerifyDesc: "消费者扫码验证商品真伪，首次验证可领取NFT",
        readyToStart: "准备好开始了吗？",
        readyToStartDesc: "加入全球商品追溯网络，让您的商品获得信任认证",
        startNow: "立即开始",
        copyright: "© 2026 ChainTrace. All rights reserved.",
    },
    en: {
        title: "Sui Product Traceability Platform",
        connectWallet: "Connect Wallet",
        pleaseConnectWallet: "Please connect your wallet",
        loading: "Loading...",
        productManagement: "📦 Product Management",
        scanner: "🔍 QR Code Scanner",
        productTraceabilityManagement: "Product Traceability Management",
        traceFlow: "Publish Product → Upload to Chain → Generate QR Code → Consumer Scan Verification",
        totalProducts: "📦 Total Products",
        pendingChain: "🟡 Pending",
        onChain: "🟢 On Chain",
        processing: "🔄 Processing",
        publishProduct: "+ Publish Product",
        searchPlaceholder: "Search product name or description...",
        all: "All",
        batchUpload: "Batch Upload",
        allProducts: "All Products",
        category: "Category",
        extendedFields: "Extended Fields",
        status: "Status",
        qrcodeCount: "QR Code Count",
        createTime: "Create Time",
        actions: "Actions",
        noProducts: "No Products",
        noProductsTip: "No products have been published yet. Click the button above to publish your first product.",
        noPendingTip: "No pending products",
        noOnChainTip: "No products on chain yet",
        tip: "💡 Tip: Upload product to chain to generate QR codes for consumer verification",
        detail: "Detail",
        upload: "Upload",
        delete: "Delete",
        generateQRCode: "Generate QR Code",
        newProduct: "New Product",
        basicInfo: "Basic Info (Required)",
        productName: "Product Name",
        productDescription: "Product Description",
        selectCategory: "Select Category",
        extendedFieldsOptional: "Extended Fields (Optional)",
        addField: "+ Add Field",
        fieldName: "Field Name",
        fieldValue: "Field Value",
        text: "Text",
        date: "Date",
        number: "Number",
        saveDraft: "Save Draft",
        saveAndUpload: "Save & Upload",
        cancel: "Cancel",
        close: "Close",
        saveChanges: "Save Changes",
        saved: "Saving...",
        uploading: "Uploading...",
        productDetail: "Product Detail",
        edit: "Edit",
        chainInfo: "On-Chain Info",
        chainId: "Chain ID",
        blockHeight: "Block Height",
        uploadTime: "Upload Time",
        statistics: "Statistics",
        scanCount: "Scan Count",
        nftClaim: "NFT Claim",
        claimNFT: "Claim NFT",
        claiming: "Claiming...",
        productVerification: "🔍 Product Verification",
        verificationDesc: "Enter QR Code ID to verify product authenticity. First scan can claim NFT.",
        enterQRCode: "Enter QR Code ID...",
        scanVerify: "Scan Verify",
        processingText: "Processing...",
        verificationResult: "Verification Result",
        productAuthentic: "✅ Authentic Product",
        productInfo: "🏷️ Product Info",
        scanHistory: "📊 Scan History",
        scannedTimes: "Scanned",
        times: "times",
        alreadyClaimed: "Claimed",
        canClaim: "Available",
        firstScanTime: "First Scan Time",
        firstScanner: "First Scanner",
        congratsFirstScan: "🎉 Congratulations! You are the first scanner, you can claim NFT",
        notFirstScan: "⚠️ You are not the first scanner, cannot claim NFT",
        nftAlreadyClaimed: "💡 NFT already claimed, you can still verify product authenticity",
        violetTheme: "🟣 Violet Theme",
        blueTheme: "🔵 Deep Blue Theme",
        chinese: "简体中文",
        english: "English",
        food: "Food",
        clothing: "Clothing",
        electronics: "Electronics",
        cosmetics: "Cosmetics",
        agricultural: "Agricultural",
        medicine: "Medicine",
        other: "Other",
        pleaseFillBasic: "Please fill in all basic information",
        pleaseEnterFieldName: "Please enter field name",
        productCreated: "Product created and uploaded to chain!",
        productSaved: "Product saved as draft!",
        fieldAdded: "Field added successfully",
        confirmDeleteField: "Are you sure you want to delete this field?",
        confirmDeleteProduct: "Are you sure you want to delete this product?",
        deleted: "Product deleted",
        cannotDeleteOnChain: "Products on chain cannot be deleted",
        uploadConfirm: "Are you sure you want to upload",
        itemsToChain: "items to chain?",
        uploadingBatch: "Batch uploading, please refresh later to check status",
        pleaseSelectProducts: "Please select products to upload first",
        qrcodeGenerated: "✅ QR Code generated successfully!",
        qrcodeId: "📋 QR Code ID",
        qrcodeTip: "💡 Please copy this ID for scan verification",
        scanning: "Uploading to chain, please refresh later to check status",
        nftClaimed: "✅ NFT claimed successfully!",
        nftId: "📋 NFT ID",
        nftProductId: "🏷️ Product ID",
        nftClaimTime: "⏰ Claim Time",
        claimFailed: "❌ Claim failed! You are not the first scanner or NFT already claimed",
        qrcodeNotFound: "❌ QR Code not found, please check the ID",
        pleaseEnterQrcode: "Please enter QR Code ID",
        scanFailed: "❌ Scan verification failed, please try again later",
        productQuantity: "📦 Product Quantity",
        quantityTip: "(max 10000)",
        qrcodeProgress: "📊 QR Code Progress",
        batchGenerateQRCode: "Batch Generate QR Codes",
        enterQrcodeCount: "Enter quantity to generate",
        remaining: "Remaining",
        allQrcodesGenerated: "⚠️ All QR Codes have been generated",
        invalidCount: "❌ Invalid quantity",
        batchQrcodeGenerated: "✅ Batch QR Codes generated successfully!",
        generatedCount: "Generated Count",
        qrcodeUrls: "QR Code Verification URLs",
        purple: "Violet Theme",
        blue: "Blue Theme",
        enterpriseInfo: "Enterprise Info",
        productCount: "Product Count",
        createdAt: "Created At",
        disconnect: "Disconnect",
        back: "Back",
        editEnterpriseProfile: "Edit Enterprise Profile",
        savedSuccessfully: "Saved successfully!",
        enterpriseName: "Enterprise Name",
        enterEnterpriseName: "Enter enterprise name",
        enterDescription: "Enter description",
        walletAddress: "Wallet Address",
        enterpriseNotFound: "Enterprise not found",
        save: "Save",
        generatedQrcodes: "Generated QR Codes",
        showQrcodes: "Show QR Codes",
        hideQrcodes: "Hide QR Codes",
        generating: "Generating",
        copyLink: "Copy Link",
        claimed: "Claimed",
        unclaimed: "Unclaimed",
        copied: "Copied!",
        home: "Home",
        dashboard: "Dashboard",
        globalPlatform: "Global Platform",
        heroTitle: "Global Product Traceability Platform",
        heroSubtitle: "Based on Sui blockchain technology, providing open, transparent, and permanently preserved product traceability solutions for enterprises worldwide",
        getStarted: "Get Started",
        scanNow: "Scan Now",
        globalCoverage: "Global Coverage",
        globalCoverageDesc: "Supports global product traceability. No matter where your products are sold, full tracking is possible",
        openTransparent: "Open & Transparent",
        openTransparentDesc: "All traceability data is stored on-chain. Anyone can verify the authenticity of product information",
        freeToUse: "Free to Use",
        freeToUseDesc: "Enterprises can create products, generate QR codes, and store on-chain for free, zero cost to start",
        chainPermanent: "Permanent On-chain Storage",
        chainPermanentDesc: "Data is stored on the blockchain, immutable and permanently preserved, ensuring long-term validity of product information",
        nftVerification: "NFT Verification",
        nftVerificationDesc: "Consumers scan to verify product authenticity, first verification can claim NFT rewards",
        fastEfficient: "Fast & Efficient",
        fastEfficientDesc: "Based on Sui blockchain's high-performance features, fast transaction confirmation, smooth experience",
        qrcodesGenerated: "QR Codes Generated",
        enterprises: "Enterprise Users",
        uptime: "Uptime",
        cost: "Cost",
        howItWorks: "How It Works",
        howItWorksDesc: "Simple four steps to complete the product traceability process",
        createProduct: "Create Product",
        createProductDesc: "Create product information in the dashboard, set product quantity and extended fields",
        uploadChain: "Upload to Chain",
        uploadChainDesc: "Upload product information to Sui blockchain, obtain on-chain ID",
        generateQrcode: "Generate QR Codes",
        generateQrcodeDesc: "Batch generate encrypted QR codes, each QR code corresponds to a unique verification link",
        scanVerifyDesc: "Consumers scan to verify product authenticity, first verification can claim NFT",
        readyToStart: "Ready to Start?",
        readyToStartDesc: "Join the global product traceability network and get trust certification for your products",
        startNow: "Start Now",
        copyright: "© 2026 ChainTrace. All rights reserved.",
    }
};

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguage] = useState<Language>(() => {
        const saved = localStorage.getItem("language");
        return (saved as Language) || "zh";
    });

    useEffect(() => {
        localStorage.setItem("language", language);
    }, [language]);

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}